BPS_IntruderConfig {
 m_sWarningTitle "AVISO - ZONA SEGURA INIMIGA"
 m_sWarningMessage "Você está dentro de uma Zona Segura inimiga. Saia imediatamente. Você será eliminado em %1 segundos."
 m_sExitTitle "ZONA SEGURA INIMIGA"
 m_sExitMessage "Você saiu da Zona Segura inimiga. Eliminação cancelada."
}