BPS_CombatConfig {
 m_sLockTitle "ZONA SEGURA - COMBATE"
 m_sLockMessage "Você atirou dentro da Zona Segura. Sua proteção foi temporariamente desativada!"
 m_sRestoredTitle "ZONA SEGURA"
 m_sRestoredMessage "Sua proteção da Zona Segura foi restaurada."
}