SCR_MilitarySupplyAllocationConfig {
 m_aMilitarySupplyAllocationRankList {
  SCR_MilitarySupplyAllocationRankInfo "{6A3359A38F1E37A3}" {
   m_eRank COLONEL
   m_iMilitarySupplyAllocationValue 375
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 375
  }
  SCR_MilitarySupplyAllocationRankInfo "{6A3359A3B6F72325}" {
   m_eRank GENERAL
   m_iMilitarySupplyAllocationValue 450
   m_iAvailableAllocatedSuppliesReplenishmentThresholdValue 450
  }
 }
}