SCR_MissionHeaderCampaign {
 World "{F4C061EC1751DA3E}Worlds/Conflict/WCS_Everon_Conflict_NvS_Layout1.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "[Divisul] Everon - North/South"
 m_sAuthor "Credtios by WCS"
 m_sDescription "ProjetoX Brasil & LATAM é uma comunidade de Arma Reforger dedicada a reunir jogadores do Brasil e da América Latina para experiências táticas, combates intensos e trabalho em equipe em um ambiente competitivo e organizado."\
 ""
 m_sIcon "{7DE2B69E827A32F5}Images/Divisul_icon.edds"
 m_sLoadingScreen "{7DE2B69E827A32F5}Images/Divisul_icon.edds"
 m_sPreviewImage "{181E6AC4B5B60394}Images/Divisul_preview.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}