SCR_MissionHeaderCampaign {
 World "{27A1EF384CA30783}worlds/DIVISUL_Campaign_HQC_Everon.ent"
 SystemsConfig "{7C9E720397CC6ACD}Configs/Systems/ConflictSystems.conf"
 m_sName "[Divisul] Everon - Norte/Sul"
 m_sAuthor "Poze"
 m_sDescription "Divisul é uma comunidade de Arma Reforger dedicada a reunir jogadores do Brasil e da América Latina para experiências táticas, combates intensos e trabalho em equipe em um ambiente competitivo e organizado."\
 ""
 m_sIcon "{7DE2B69E827A32F5}Images/Divisul_icon.edds"
 m_sLoadingScreen "{7DE2B69E827A32F5}Images/Divisul_icon.edds"
 m_sPreviewImage "{181E6AC4B5B60394}Images/Divisul_preview.edds"
 m_sGameMode "#AR-Campaign_GamemodeName"
 m_iPlayerCount 128
 m_eEditableGameFlags 6
 m_eDefaultGameFlags 6
}